import './globals.css';
import { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import { CustomRouterProvider } from '$/contexts/CustomRouterContext';

const inter = Inter({ subsets: ['latin', 'vietnamese'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <CustomRouterProvider>{children}</CustomRouterProvider>
            </body>
        </html>
    );
}
